"""
Django settings for gods_acre project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mma*a=-f8f@*7aijefemjfly@3epbofcug*^fq5os)6)+30w^z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jet',  # django-jet: has to be before admin
    'admin_reorder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cemetery',  # mine

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'gods_acre.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gods_acre.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# Model-admin Reorder
# https://github.com/mishbahr/django-modeladmin-reorder
# TODO fix breadcrumb to say "cemetery" at http://127.0.0.1:8000/admin/cemetery/ instead of "general ownership"
ADMIN_REORDER = (
    'auth',

    # General
    {'app': 'cemetery', 'label': 'General', 'models': [
        'cemetery.Spot',
    ]},

    # Ownership
    {'app': 'cemetery', 'label': 'Ownership', 'models': [
        'cemetery.Deed',
        {'model': 'cemetery.OwnershipReceipt', 'label': 'Receipts'},
        'cemetery.Owner',
    ]},

    # Operations
    {'app': 'cemetery', 'label': 'Operations', 'models': [
        'cemetery.Operation',
    ]},

    # Constructions
    {'app': 'cemetery', 'label': 'Constructions', 'models': [
        'cemetery.Construction',
        'cemetery.Authorization',
        {'model': 'cemetery.Company', 'label': 'Companies'}
    ]},

    # Payments
    {'app': 'cemetery', 'label': 'Payments', 'models': [
        'cemetery.Payment',
        {'model': 'cemetery.PaymentReceipt', 'label': 'Receipts'},
    ]},

    # Maintenance
    {'app': 'cemetery', 'label': 'Maintenance', 'models': [
        'cemetery.Maintenance',
    ]},
)
